# Generated by Django 2.1.13 on 2019-12-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_delete',
            new_name='is_select',
        ),
    ]
