# Generated by Django 2.1.13 on 2019-12-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20191220_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='goods',
        ),
    ]
