# Generated by Django 2.1.13 on 2019-12-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='product_name',
            new_name='goods_name',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='product_no',
            new_name='goods_no',
        ),
        migrations.RemoveField(
            model_name='mainshow',
            name='name',
        ),
    ]
