# Generated by Django 2.1.13 on 2019-12-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191218_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainshow',
            name='goods_no',
        ),
    ]
