# Generated by Django 2.1.13 on 2019-12-21 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_mainshow_goods_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
