# Generated by Django 2.1.13 on 2019-12-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_mainshow_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshow',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
